{% set version = "0.8.0" %}

{% set PYTHON = PYTHON | default("$PYTHON") %}
{% set python_min = python_min | default("3.9") %}

package:
  name: fastapi_utils-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/fastapi-utils/fastapi_utils-{{ version }}.tar.gz
  sha256: eca834e80c09f85df30004fe5e861981262b296f60c93d5a1a1416fe4c784140

build:
  noarch: python
  number: 0

outputs:
  - name: fastapi_utils-core
    build:
      noarch: python
      script:
        - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - poetry-core >=1.0.0
      run:
        - fastapi >=0.89,<1.0
        - pydantic >=1.0,<3.0
        - python >={{ python_min }}
        - psutil >=5,<6
        # upstream claims is optional, but does not import without
        - typing_inspect >=0.9.0,<0.10.0
      run_constrained:
        - {{ pin_subpackage("fastapi_utils", max_pin="x.x.x") }}
        - sqlalchemy >=1.4,<3.0.0
        - pydantic-settings >=2.0.1,<3.0.0
    test:
      requires:
        - pip
        - python {{ python_min }}
      imports:
        - fastapi_utils
      commands:
        - pip check

  - name: fastapi_utils-with-session
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("fastapi_utils-core", max_pin="x.x.x") }}
        - sqlalchemy
    test:
      imports:
        - fastapi_utils.session
      commands:
        - pip check
      requires:
        - pip

  - name: fastapi_utils-with-all
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("fastapi_utils-with-session", max_pin="x.x.x") }}
        - pydantic-settings
    test:
      imports:
        - fastapi_utils
        - fastapi_utils.api_settings
      commands:
        - pip check
      requires:
        - pip

  - name: fastapi_utils
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("fastapi_utils-with-session", max_pin="x.x.x") }}
    test:
      imports:
        - fastapi_utils
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://fastapi-utils.davidmontague.xyz
  summary: Reusable utilities for FastAPI
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/dmontagu/fastapi-utils

extra:
  feedstock-name: fastapi_utils
  recipe-maintainers:
    - marcelotrevisani
    - bollwyvl
