{% set version = "0.6.0" %}

# handle undefined PYTHON in `noarch: generic` outputs
{% if PYTHON is not defined %}{% set PYTHON = "$PYTHON" %}{% endif %}

package:
  name: fastapi_utils-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/fastapi-utils/fastapi_utils-{{ version }}.tar.gz
  sha256: 4fd34ff7d3bcc8e31fd5c5a9c66c16ca09093e3d97663ed7e3bf013b380766a9

build:
  noarch: python
  number: 0

outputs:
  - name: fastapi_utils-core
    build:
      noarch: python
      script:
        - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
    requirements:
      host:
        - pip
        - python >=3.7,<4.0
        - poetry-core >=1.0.0
      run:
        - fastapi >=0.89,<1.0
        - pydantic >=1.0,<3.0
        - python >=3.7,<4.0
        - psutil >=5,<6
        # upstream claims is optional, but does not import without
        - typing_inspect >=0.9.0,<0.10.0
      run_constrained:
        - {{ pin_subpackage("fastapi_utils", exact=True) }}
        - sqlalchemy >=1.4,<2.0.0
        - pydantic-settings >=2.0.1,<3.0.0
    test:
      imports:
        - fastapi_utils
      commands:
        - pip check
      requires:
        - pip

  - name: fastapi_utils-with-session
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("fastapi_utils-core", exact=True) }}
        - sqlalchemy
    test:
      imports:
        - fastapi_utils.session
      commands:
        - pip check
      requires:
        - pip

  - name: fastapi_utils-with-all
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("fastapi_utils-with-session", exact=True) }}
        - pydantic-settings
    test:
      imports:
        - fastapi_utils
        - fastapi_utils.api_settings
      commands:
        - pip check
      requires:
        - pip

  - name: fastapi_utils
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("fastapi_utils-with-session", exact=True) }}
    test:
      imports:
        - fastapi_utils
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://fastapi-utils.davidmontague.xyz
  summary: Reusable utilities for FastAPI
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/dmontagu/fastapi-utils

extra:
  feedstock-name: fastapi_utils
  recipe-maintainers:
    - marcelotrevisani
    - bollwyvl
