{% set name = "fastapi_utils" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4fd34ff7d3bcc8e31fd5c5a9c66c16ca09093e3d97663ed7e3bf013b380766a9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry
  run:
    - fastapi
    - pydantic >=1.0,<2.0
    - python >=3.6,<4.0
    - sqlalchemy >=1.3.12,<2.0.0

test:
  imports:
    - fastapi_utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://fastapi-utils.davidmontague.xyz
  summary: Reusable utilities for FastAPI
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
